global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'monitoring/grafana'
    static_configs:
    - targets: ['grafana:3000']
  - job_name: 'monitoring/prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'monitoring/loki'
    static_configs:
    - targets: ['loki:3100']
  - job_name: 'monitoring/tempo'
    static_configs:
    - targets: ['tempo:80']
  - job_name: monitoring/otel
    scrape_interval: 5s
    static_configs:
    - targets:
      - otel:8888
      - otel:8889

