{
 "title": "RED",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (operation)(rate(calls_total{operation=\"/otel-demo\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Example.com Response Time (p99)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(latency_bucket{operation=\"HTTP GET\", http_url=\"http://example.com\"}[$__rate_interval])) by (le))",
     "legendFormat": "GET example.com"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (operation) (rate(calls_total{operation=\"/otel-demo\", status_code=\"STATUS_CODE_ERROR\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Db Query Duration (p99)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(latency_bucket{operation=\"oteldemodb\"}[$__rate_interval])) by (le))",
     "legendFormat": "oteldemodb"
    }
   ]
  },
  {
   "title": "Duration (p99)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99, sum(rate(latency_bucket{operation=\"/otel-demo\"}[$__rate_interval])) by (le))",
     "legendFormat": "/otel-demo"
    }
   ]
  },
  {
   "title": "Arbitrary Counter",
   "type": "stat",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "arbitary_count_total", "legendFormat": "{{service_name}}" }
   ]
  }
 ]
}