apiVersion: 1
datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    apiVersion: 1
    jsonData:
      derivedFields:
        - name: TraceID
          datasourceUid: tempo
          matcherRegex: '"traceid":"(\w+)"'
          url: $${__value.raw}
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo/
    access: proxy
    editable: true
    isDefault: false
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: "loki"
        filterBySpanID: true
        filterByTraceID: true
        mapTagNamesEnabled: true
        mappedTags:
          - key: service.name
            value: service_name
        spanEndTimeShift: "1s"
    version: 1
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090/
    access: proxy
    editable: true
    isDefault: true
    version: 1
    jsonData:
      timeInterval: 60s
      httpMethod: GET
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
