receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  logging:
    loglevel: debug
  loki:
    endpoint: "http://loki:3100/api/prom/push"
  otlp:
    endpoint: "tempo:4317"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "otel"
    resource_to_telemetry_conversion:
      enabled: true
    enable_open_metrics: true

processors:
  batch:
  spanmetrics:
    metrics_exporter: prometheus
    dimensions:
      - name: http.url
      - name: http.status_code
      - name: db.system
  resource:
    attributes:
      - action: insert
        key: service_name
        from_attribute: service.name
      - action: insert
        key: service_namespace
        from_attribute: service.namespace
      - action: insert
        key: service_instance_id
        from_attribute: service.instance.id
      - action: insert
        key: service_version
        from_attribute: service.version
      - action: insert
        key: loki.resource.labels
        value: service_name, service_namespace, service_instance_id, service_version

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [logging, loki]
    traces:
      receivers: [otlp]
      exporters: [logging, otlp]
      processors: [spanmetrics, batch]
    metrics:
      receivers: [otlp]
      exporters: [logging, prometheus]
      processors: [batch]
